#! /bin/bash

# configurations in /etc/profile
sudo cat etc-profile.backup >> /etc/profile

# configurations in /etc/apt/sources.list
sudo cat etc-apt-sources.list.backup >> /etc/apt/sources.list

# configurations in /etc/sysctl.conf
sudo cat etc-sysctl.conf.backup >> /etc/sysctl.conf


# ubuntu tweak repository
sudo add-apt-repository ppa:tualatrix/ppa

# update due to the edition of /etc/apt/sources.list and the use of add-apt-repository command
sudo aptitude update


# and the installation begins!
## utils
sudo aptitude install -y ubuntu-tweak gnome-do parcellite checkgmail nicotine sound-juicer mp3gain easytag guake

## nautilus plugins
nautilus-open-terminal nautilus-wallpaper nautilus-script-audio-convert nautilus-image-converter

## messengers
sudo aptitude install -y emesene pidgin

## multimedia
sudo aptitude install -y gstreamer0.10-ffmpeg gstreamer0.10-plugins-ugly gstreamer0.10-plugins-ugly-multiverse gstreamer0.10-plugins-bad gstreamer0.10-plugins-bad-multiverse gstreamer0.10-plugins-good vlc

## compactors
sudo aptitude install -y rar unrar cabextract

## development
sudo aptitude install -y ruby irb ri rubygems ssh git-core


# finally, getting the newest versions
sudo aptitude safe-upgrade
