#! /bin/bash

# configurations in /etc/profile
sudo cat etc-profile.backup >> /etc/profile

# configurations in /etc/apt/sources.list
sudo cat etc-apt-sources.list.backup >> /etc/apt/sources.list

# adding keys for icon theme, ubuntu-tweak, compact nautilus
sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 0x1781bd45c4c3275a34bb6aec6e871c4a881574de
sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com FE85409EEAB40ECCB65740816AF0E1940624A220
sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 0x57a9d237d39498ec69fa7a531b5cf8cc9a93a0ab

# update due to the edition of /etc/apt/sources.list
sudo apt-get update

# icon theme
sudo aptitude install icon-wild-shine-theme

# ubuntu tweak
sudo apt-get install ubuntu-tweak
sudo apt-get dist-upgrade

# some useful applications
sudo apt-get install gnome-do parcellite checkgmail nautilus-open-terminal gwibber

# multimedia
sudo apt-get install gstreamer0.10-ffmpeg gstreamer0.10-plugins-ugly gstreamer0.10-plugins-bad mp3gain easytag

# packages
sudo apt-get install rar unrar cabextract

# programming
sudo apt-get install ruby irb ri rubygems ssh git-core sun-java6-jdk sun-java6-plugin
